site :opscode



cookbook 'mysql', git: 'https://github.com/ScholzVolkmer/mysql.git'
cookbook 'logrotate', git: 'https://github.com/ScholzVolkmer/logrotate.git'
cookbook 'pacman', git: 'https://github.com/ScholzVolkmer/pacman.git'
cookbook 'postgresql', git: 'https://github.com/ScholzVolkmer/python.git'
cookbook 'application', git: 'https://github.com/ScholzVolkmer/application.git'
cookbook 'application_python', git: 'https://github.com/ScholzVolkmer/application_python'
cookbook 'supervisor', git: 'https://github.com/ScholzVolkmer/supervisor.git'
cookbook 'git', git: 'https://github.com/ScholzVolkmer/git.git'
cookbook 'runit', git: 'https://github.com/ScholzVolkmer/runit.git'
cookbook 'nginx_conf', git: 'https://github.com/ScholzVolkmer/chef-nginx_conf.git'

cookbook 'apache2'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'iptables'
cookbook 'openssl'
cookbook 'aws'
cookbook 'xfs'
cookbook 'mysql-chef_gem'
cookbook 'database'
cookbook 'gunicorn'
cookbook 'yum-epel'
cookbook 'dmg'
cookbook 'windows'
cookbook 'yum'
cookbook 'nginx'
cookbook 'bluepill'
cookbook 'ohai'
cookbook 'rsyslog'

cookbook 'mysql-databases', path: 'chef/cookbooks/mysql-databases/'
cookbook 'django_project_template', path: 'chef/cookbooks/django_project_template/'